# Generated by Django 3.0.5 on 2020-04-30 00:30

import cropperjs.models
from django.db import migrations
import uuid_upload_path.storage


class Migration(migrations.Migration):

    dependencies = [
        ('qtadmin', '0003_auto_20200429_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quetziadmin',
            name='image',
            field=cropperjs.models.CropperImageField(blank=True, null=True, upload_to=uuid_upload_path.storage.upload_to, verbose_name='Foto de perfil'),
        ),
    ]
