# Generated by Django 3.0.5 on 2020-04-29 23:20

from django.db import migrations, models
import uuid_upload_path.storage


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_auto_20200429_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=uuid_upload_path.storage.upload_to, verbose_name='foto de perfil'),
        ),
    ]
