# Generated by Django 3.0.4 on 2020-03-27 21:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        ('qtadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(verbose_name='Descripción')),
                ('progress', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje')),
                ('initialDate', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de inicio')),
                ('finalDate', models.DateField(verbose_name='Fecha estimada de finalización')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('boss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_boss', to='qtadmin.QuetziAdmin', verbose_name='Jefe del Proyecto')),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='business.Business', verbose_name='Empresa')),
                ('members', models.ManyToManyField(related_name='get_p_members', to='qtadmin.QuetziAdmin', verbose_name='Integrantes')),
            ],
            options={
                'verbose_name': 'proyecto',
                'verbose_name_plural': 'proyectos',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(verbose_name='Descripción')),
                ('initialDate', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de inicio')),
                ('finalDate', models.DateField(verbose_name='Fecha estimada de finalización')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('members', models.ManyToManyField(related_name='get_hw_members', to='qtadmin.QuetziAdmin', verbose_name='Integrantes')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project', verbose_name='Tarea')),
            ],
            options={
                'verbose_name': 'tarea',
                'verbose_name_plural': 'tareas',
                'ordering': ['-created'],
            },
        ),
    ]
